name: GitHub-Profile-3D-Contrib

# 03:00 JST == 18:00 UTC
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

# 1) define que o GITHUB_TOKEN pode escrever no repositório
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # 2) usa checkout@v4 e injeta token automaticamente
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:   ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "generated" || echo "nothing to commit"
          git push
